import icons from '../img/icons.svg';
import './components/refs';
import './api';
import './exercises-section/filter-cards';
import './subscribe';
import './quote';
import './components/fn-helpers';
import './review';
import './rating';
import './exercises-section/pagination';
import './exercises-section/exercise-modal';
import './exercises-section/exercise-modal-template';
import './notiflix';
import './components/mode';
// import './js/scroll-up';
import './exercises-section/exercises-cards';
import './scrolls';
import './mobile-menu.js';
import './info';
import './search';
