import './js/components/refs';
import './js/api';
import './js/exercises-section/filter-cards';
import './js/subscribe';
import './js/quote';
import './js/components/fn-helpers';
import './js/exercises-section/exercise-modal';
import './js/exercises-section/exercise-modal-template';
import './js/notiflix';
// import './js/scroll-up';
import './js/exercises-cards';
import './js/scrolls';
import './js/mobile-menu.js';
import './js/info';
