import './js/refs';
import './js/api';
import './js/filter-cards';
import './js/components/subscribe';
import './js/quote';
import './js/fn-helpers';
import './js/exercise-modal';
import './js/exercuse-modal-template';
import './js/notiflix';
import './js/scroll-up'
